### ISSUE TITLE
Plugin tries to create discussion when it's configured not to

### ISSUE THREAD

**Issue by TimothyGillespie** [woodpecker-ci/plugin-github-release#59]
I tried to use the plugin and it did unfortunately not work for me.

The configuration file is as follows (the release step is the last one):

```yaml
variables:
  cypress_browser_image: &cypress_browser_image 'cypress/included:cypress-13.6.6-node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1'
  alpine: &alpine 'alpine:3.19.1'
  start_server: &start_server
    - npm run dev-server &

when:
  event: [push, pull_request, tag]

steps:
  - name: install
    image: *cypress_browser_image
    commands:
      - npm install

  - name: build
    image: *cypress_browser_image
    commands:
      - npm run build
      - npm run prepare-dev

  - name: test_chrome
    image: *cypress_browser_image
    commands:
      - <<: *start_server
      - npx cypress run --browser chrome
    when:
      - status: [ success, failure ]

  - name: test_firefox
    image: *cypress_browser_image
    commands:
      - <<: *start_server
      - npx cypress run --browser firefox
    when:
      - status: [ success, failure ]

  - name: test_edge
    image: *cypress_browser_image
    commands:
      - <<: *start_server
      - npx cypress run --browser edge
    when:
      - status: [ success, failure ]

  - name: archiving
    image: *alpine
    commands:
      - apk add tar zip
      - mkdir -p dist/archives
      - find dist/prod -type f -printf "%P\n" | tar -czf "dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-prod.tar.gz" -C dist/prod -T -
      - find dist/lib -type f -printf "%P\n" | tar -czf "dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-lib.tar.gz" -C dist/lib -T -
      - find dist/prod -type f -exec sh -c "zip dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-prod.zip -j {}" \;
      - find dist/lib -type f -exec sh -c "zip dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-lib.zip -j {}" \;
    when:
      event: tag

  - name: create_release
    image: woodpeckerci/plugin-github-release
    settings:
      discussion-category: ""
      files:
        - dist/archives/*.tar.gz
        - dist/archives/*.zip
      title: ${CI_COMMIT_TAG##v}
      api-key:
        from_secret: FOSSalyze_RELEASE_GITHUB_TOKEN
    when:
      event: tag
```

I have previously not specified the `discussion-category`. It has shown the same problem, though.

In the create_release step I have the following log entries:

```txt
no existing release (draft) found for the given tag
Release v0.1.0 identified as a full release
Release v0.1.0 will be created and published
Not creating a discussion
Release v0.1.0 automatically will not generate release notes
time="2024-02-28T20:57:26Z" level=error msg="execution failed: failed to create the release: failed to create or edit a release: failed to create release: POST https://api.github.com/repos/FOSSalyze/privacy-friendly-iframe/releases: 404 Discussion could not be created. Make sure you passed a valid category name. []"
```

Here it states "Not creating a discussion" as I would expect it to. Later on it seems to still attempt to create the discussion and fails consequently.

The release is created. However, the files are missing - which seems quite plausible as it apparently fails halfway through after creating the release but before uploading the files.
